### ISSUE TITLE
Change code

### ISSUE THREAD

**Issue by paololec** [spjeff/sppatchify#1]
Maybe can be usefull using  Upgrade-SPContentDatabase before configuration wizard intead unmount and then mount contentdb.

**Comment by rolandon** [comment]
@spjeff  thanks for the responds advising to comment out lines 1036 and 1044 to bypass taking the DB offline. However like @paololec just suggested would be a better option for me. I tried the script it works perfect, however the DB did not get upgraded. Can you provide a updated script to upgrade the DB verus taken them offline?
Thanks.

**Comment by spjeff** [comment]
Thanks guys.   Optional cmd switch parameter sounds good here.

**"-o"** will now keep databases online and bypass the Dismount/Mount steps.

Committed change to PS1 and updated release download ZIP too.  =)

https://github.com/spjeff/sppatchify/commit/a167cea3f69cef4650f4eda82a679cca1e461abe#diff-5918760c8d2458204dcbb74d9364e7d7

**Comment by rolandon** [comment]
Thanks @spjeff
