### ISSUE TITLE
Email option

### ISSUE THREAD

**Issue by rolandon** [spjeff/sppatchify#11]
Hello,
is there a way to have the script send a email if something fails during the process? I would like to get an email sent if there is an issue and after the patching is completed.

**Comment by spjeff** [comment]
Good idea.

I found sample PowerShell code at https://blogs.msdn.microsoft.com/vijaysk/2008/04/08/automatically-email-powershell-session-transcript/ and merged into the main PS1 with version 0.71

Would you please download the latest and test?

.\SPPatchify.ps1 -emailReportTo "somebody@company.com" -emailReportFrom "sharepoint@company.com -emailReportServer "mailrelay.company.com"

**Comment by rolandon** [comment]
I get the below error 


.\SPPatchify.ps1 -emailReportTo "test@company.com"
.\SPPatchify.ps1 : A positional parameter cannot be found that accepts
argument 'test@company.com'.
At line:1 char:1
+ .\SPPatchify.ps1 -v -emailReportTo "test@company.com" -emailReportFrom "te ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [SPPatchify.ps1], ParameterB
   indingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,SPPatchify.ps1

**Comment by spjeff** [comment]
Updated params from [switch] to [string].

Please test again.

https://github.com/spjeff/sppatchify/releases/download/v0.71/SPPatchify.zip
