### ISSUE TITLE
Wrong Product Detection in Line 895

### ISSUE THREAD

**Issue by HenrikDamslund** [spjeff/sppatchify#13]
Hi,

When detecting product in Line 895
$sppl = (Get-SPProduct -Local) \|? {$_.ProductName -like "*Project*"}
You will get a wrong product retuened if you have previously installed a localized Languagepack:

In an environment the result of Get-SPProduct is:
Language Pack for SharePoint and Project Server 2013  - Danish/dansk	True	
Microsoft SharePoint Server 2013	True	

This means that SPPatchify wrongly will report that it is SharePoint Project Server (PROJ15) that is installed.

The query should be:
$sppl = (Get-SPProduct -Local) \|? {$_.ProductName -like "*Microsoft Project*"}

![wrongspproduct](https://user-images.githubusercontent.com/35597532/35146965-22d73226-fd0d-11e7-95b0-8bde7e61907f.png)

**Comment by spjeff** [comment]
Sharp eye.   Yes, you are correct.  Most of my farms are English only so didn't notice during testing.  Thank you for catching this.

Updated PS1 and primary release ZIP.

**Comment by HenrikDamslund** [comment]
This is not fixed in latest release V.0.99

**Comment by spjeff** [comment]
Thanks Henrik.

Fixed with latest commit.

https://github.com/spjeff/sppatchify/commit/46c4bae6b2c2c153d4d7084a3607768e636b7f1f#diff-5918760c8d2458204dcbb74d9364e7d7
