### ISSUE TITLE
Creating remote session on servers fails

### ISSUE THREAD

**Issue by zenaidura** [spjeff/sppatchify#14]
![capture](https://user-images.githubusercontent.com/9323267/36617520-b6c10f0c-18b5-11e8-996e-4e8f21c951fb.PNG)

While doing the pre-flight check and make sure the remoting in to server is enabled.. 
```
function PreflightCheck() {
    try {
        Write-Host "Starting preflight check " -Fore Green
        # Start Jobs
        foreach ($server in $global:servers) {
            $addr = $server.Address
            if ($addr -ne $env:computername) {
                **$s = New-PSSession -ComputerName $env:computername -Credential $global:cred -Authentication CredSSP**
            }
        }
```
The line which is bold above needs to be modified to:
`   **$s = New-PSSession -ComputerName $addr  -Credential $global:cred -Authentication CredSSP**
`

> I cannot believe that this was not caught while testing your script to connect to servers.

**Comment by SparkDustJoe** [comment]
This code appears to have been updated, does this issue still need to remain open?

    function PreflightCheck() {
        try {
            Write-Host "Check Remote PowerShell " -Fore Green
            # Start Jobs
            foreach ($server in $global:servers) {
                $addr = $server.Address
                if ($addr -ne $env:computername) {
    		# Dynamic open PSSession
                    if ($remoteSessionPort -and $remoteSessionSSL) {
                        $remote = New-PSSession -ComputerName $addr -Credential $global:cred -Authentication Credssp -Port $remoteSessionPort -UseSSL
                    }
                    elseif ($remoteSessionPort) {
                        $remote = New-PSSession -ComputerName $addr -Credential $global:cred -Authentication Credssp -Port $remoteSessionPort
                    }
                    elseif ($remoteSessionSSL) {
                        $remote = New-PSSession -ComputerName $addr -Credential $global:cred -Authentication Credssp -UseSSL
                    }
                    else {
                        $remote = New-PSSession -ComputerName $addr -Credential $global:cred -Authentication Credssp
                    }
                }
            }
            Write-Host "Succeess" -Fore Green
            return $true
        }
        catch {
            throw 'Not able to connect to one or more computers in the farm. Please make sure you have run run Enable-PSRemoting and Enable-WSManCredSSP -Role Server'
        }
    }

**Comment by spjeff** [comment]
Resolved with above code.  Issue closed.
