### ISSUE TITLE
Check for new CSV??

### ISSUE THREAD

**Issue by tommls** [spjeff/sppatchify#17]
Please consider adding code thats does some or all of this:
1) echo 'check for new csv list of patches'
2) checks if network can touch Internet -- if not, exit with message no internet available
3) else echo 'new list found,' get and use csv
OR
also other ways to check for newest csv or whatever is the best way to maintain current patch list??
Thank you for your consideration. :)

**Comment by spjeff** [comment]
Thanks tommls.

If you run "SPPatchify.ps1 -d" that will prompt the download and remove old media.

However, some admins have limited Internet access to servers and even prefer to download EXE elsewhere.   Auto detection of "\media\*.EXE" helps those admins avoid the direct Internet download.

Different scenarios and script supports both.

**Comment by tommls** [comment]
Thank you for explaining!!


Where/how is best to report problems with the script??

?It's not working properly for me. ?

This is a single-server SP2016 dev/test install, it should not be doing this...

This screenshot taken at about 725 pm, almost 3 hours after starting the script.

Fortunately I snapshotted the server so I can roll back...image file attached.


Thank you, Tom


[cid:7fcf8227-2344-4f2e-ad19-89836ee34887]

Tom Lyczko
IT Coordinator
North Country MSO
Mountain Lake Services
518-546-1122
MountainLakeServices.org
EssexIndustries.org
MountainWeaversGuild.com
________________________________
