### ISSUE TITLE
Function Error in "Register and Start SCHTASK

### ISSUE THREAD

**Issue by HenrikDamslund** [spjeff/sppatchify#20]
When run, this error is in the Section where the scheduled task is registered:

Monitor SCHTASK - SRV-XXXX.Get-ScheduledTask : SRV-XXXX: No MSFT_ScheduledTask objects found with property 'TaskName' equal to 'SPPatchify'.

Verify the value of the property and retry.
At C:\SPPatchify\SPPatchify.ps1:243 char:27
+                 $state = (Get-ScheduledTask -TaskName $taskName -CimSession $add ...
+                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (SPPatchify:String) [Get-ScheduledTask], CimJobException
    + FullyQualifiedErrorId : CmdletizationQuery_NotFound_TaskName,Get-ScheduledTask
    + PSComputerName        : SRV-XXXX

Register and start SCHTASK - SRV-XXXX - C:\SPPatchify\media\ubersrv2013-kb4018348-fullfile-x64-glb.exe
Register-ScheduledTask : Cannot validate argument on parameter 'Password'. The argument is null or empty. Provide an agument that is not null or empty, and then try the command again.
At C:\SPPatchify\SPPatchify.ps1:232 char:85
+ ... task -Password $pw -User $user -CimSession $addr
+                    ~~~
    + CategoryInfo          : InvalidData: (:) [Register-ScheduledTask], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Register-ScheduledTask

**Comment by spjeff** [comment]
Thanks Henrik.

Updated for better SCHTASK detection on former line 243.

Updated EXE run on former line 232 to run as System only.
