### ISSUE TITLE
mounting content fails when there was only one database

### ISSUE THREAD

**Issue by malterad** [spjeff/sppatchify#27]
I had the rather uncommon situation, that my farm contained only one content database before patching. In that case, when SPPatchify imports the csv, Import-Csv returns an object rather than an array. (which causes the iteration to iterate through the object properties rather the array items plus calculating the percentage fails with a 'division by zero' as $db.Count is undefined).

I suggest the following fix (which ensures that $dbs is always an array):
$dbs = @()
$dbs += Import-Csv $files.Fullname

**Comment by spjeff** [comment]
Excellent suggestion.  

Updated PS1 and commit done.

https://github.com/spjeff/sppatchify/commit/2fddbfac85bcb83ea65dcda2b91e99214efdbf23#diff-5918760c8d2458204dcbb74d9364e7d7
