### ISSUE TITLE
function defined twice: LaunchPhaseThree

### ISSUE THREAD

**Issue by malterad** [spjeff/sppatchify#28]
https://github.com/spjeff/sppatchify/blob/7e1ee0f49ff33f69be589fde4e23e522005faf31/SPPatchify.ps1#L1356-L1358

this function is defined twice (and the one linked above has a bug anyway ($scriptFile is not defined), so it should be removed.

**Comment by spjeff** [comment]
Thank you.  Updated and resolved.
