### ISSUE TITLE
offline install

### ISSUE THREAD

**Issue by SirJoeBlack** [spjeff/sppatchify#5]
hi does this work with an offline update ? how do I skip the download  of the cu as I already have it downloaded

**Comment by spjeff** [comment]
Yes Joe.  That is supported.

"SPPatchify.ps1 -D" will run download only.  I've run this on my local Win10 PC then copy the folder to a SharePoint server.

Running "SPPatchify.ps1" after will begin the patching process on the SharePoint server using the \media\ folder CU contents available locally.  No Internet connection required.

Did you try those steps?   Or see any errors?  Glad to help troubleshoot.
