### ISSUE TITLE
Struck on wait EXE stage

### ISSUE THREAD

**Issue by jmajeti** [spjeff/sppatchify#9]
We have performed the sppatchify on couple farms and both times it struck when executing the exe . we wait for couple hours to see if the executed finishes, but no luck.

Any recommendations

![2017-07-19_14-00-28](https://user-images.githubusercontent.com/17678936/28382141-2948f65c-6c8b-11e7-9be5-63ac5a885129.png)

**Comment by jmajeti** [comment]
Its sitting idle in the background.

![image](https://user-images.githubusercontent.com/17678936/28382243-7e9139f8-6c8b-11e7-8c25-a7c24fd9088a.png)

**Comment by spjeff** [comment]
Thanks for screenshot.  Looks good overall.  I have a few ideas:

1. Path contains spaces "D:\Software\SPPatchify (1)\"    Try renaming folder to remove spaces.  Should be supported OK, but helps rule out any folder path confusion.
2. PACKAGE.BYPASS.DETECTION.CHECK might be the reason why it gets stuck.   Was in older releases. https://github.com/spjeff/sppatchify/blob/master/SPPatchify.ps1#L189

Please download the current latest ZIP.  

https://github.com/spjeff/sppatchify/releases

**Comment by Triaxout** [comment]
I faced exact the same issue with version 0.67. The script got stucked at the bypass.detection.check. @jmajeti , just run the script with the parameter -bypass to run the package insatllation without the bypass check.

**Comment by spjeff** [comment]
Sounds good.  Yes, I ran into the same issue.

I believe this was inadvertently added while troubleshooting a partial EXE install (force install, by pass check, and that's how it made it's way here.)

**Comment by jmajeti** [comment]
Hi Jeff,

Should I have to run the new version with any parameters ? I have tried the new version 
you have provided it passed the exe , but I think it just bypassed the exe installation but never installed . Later it struck at the get-spproduct command and never passed to the next step . 

![2017-07-22_11-05-17](https://user-images.githubusercontent.com/17678936/28492266-ebeebad6-6ecd-11e7-82a7-30bf28faa725.png)
[SPPatchify-2017-07-21-08-43-28.txt](https://github.com/spjeff/sppatchify/files/1167434/SPPatchify-2017-07-21-08-43-28.txt)

**Comment by spjeff** [comment]
Are there any LOGs available in the folder on the remote machine "SP-DEVAPP1" under the "..\SPPatchify\LOG\" folder?

That's odd for sure.  The EXE should be visible on Task Manager with CPU % moving (to show activity).

**Comment by zaarin2k** [comment]
I also have this issue with 0.67 trying to patch SharePoint 2013.

**Comment by spjeff** [comment]
Thanks zaarin2k.

Please download the latest release and run a fresh new test.   Should resolve any issues.
